/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diwadikswobarg;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.HashSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;




/**
 *
 * @author DawidGrabowski
 */
public class Simple_Epos_System extends javax.swing.JFrame {

    private Basket basket = new Basket();
    /**
     * Creates new form Simple_Epos_System
     */
    public Simple_Epos_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblApplicationName = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        pnlMain = new javax.swing.JTabbedPane();
        pnlOrder = new javax.swing.JPanel();
        lblQuantity = new javax.swing.JLabel();
        lblProductAndPrice = new javax.swing.JLabel();
        lblShoppingCart = new javax.swing.JLabel();
        cmbQuantity = new javax.swing.JComboBox<>();
        cmbProductPrice = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaShoppingCart = new javax.swing.JTextArea();
        btnAddToCart = new javax.swing.JButton();
        btnClearList = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        lblSalesTotalName = new javax.swing.JLabel();
        lblSalesTotal = new javax.swing.JLabel();
        lblSelectedTotal = new javax.swing.JLabel();
        pnlReport = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaReport = new javax.swing.JTextArea();
        btnClearReport = new javax.swing.JButton();
        btnDownloadReport = new javax.swing.JButton();
        lblTotalNumberOfSales = new javax.swing.JLabel();
        lblAverageSale = new javax.swing.JLabel();
        lblMinimumSale = new javax.swing.JLabel();
        lblHighestSale = new javax.swing.JLabel();
        lblTotalSalesReport = new javax.swing.JLabel();
        lblTotalCustomers = new javax.swing.JLabel();
        lblReportBox = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblApplicationName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblApplicationName.setText("Simple EPOS System");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vending 32px.png"))); // NOI18N

        lblQuantity.setText("Quantity");

        lblProductAndPrice.setText("Product : Price");

        lblShoppingCart.setText("Shopping Cart");

        cmbQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQuantityActionPerformed(evt);
            }
        });

        cmbProductPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductPriceActionPerformed(evt);
            }
        });

        txtAreaShoppingCart.setColumns(20);
        txtAreaShoppingCart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAreaShoppingCart.setRows(5);
        txtAreaShoppingCart.setEnabled(false);
        jScrollPane1.setViewportView(txtAreaShoppingCart);

        btnAddToCart.setText("Add To Shop List");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        btnClearList.setText("Clear Shopping Cart");
        btnClearList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearListActionPerformed(evt);
            }
        });

        btnCheckOut.setText("Check out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        lblSalesTotalName.setText("Sales Total");

        lblSelectedTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlOrderLayout = new javax.swing.GroupLayout(pnlOrder);
        pnlOrder.setLayout(pnlOrderLayout);
        pnlOrderLayout.setHorizontalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlOrderLayout.createSequentialGroup()
                            .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblQuantity)
                                .addComponent(cmbQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblProductAndPrice)
                                .addComponent(cmbProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlOrderLayout.createSequentialGroup()
                            .addComponent(btnAddToCart)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnClearList)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCheckOut)))
                    .addComponent(lblSelectedTotal))
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShoppingCart)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSalesTotalName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSalesTotal)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlOrderLayout.setVerticalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantity)
                            .addComponent(lblProductAndPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118)
                        .addComponent(lblSelectedTotal))
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addComponent(lblShoppingCart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddToCart)
                    .addComponent(btnClearList)
                    .addComponent(btnCheckOut)
                    .addComponent(lblSalesTotalName)
                    .addComponent(lblSalesTotal))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlMain.addTab("Order", pnlOrder);

        txtAreaReport.setColumns(20);
        txtAreaReport.setRows(5);
        txtAreaReport.setEnabled(false);
        jScrollPane2.setViewportView(txtAreaReport);

        btnClearReport.setText("Clear Report");
        btnClearReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearReportActionPerformed(evt);
            }
        });

        btnDownloadReport.setText("Download Report");
        btnDownloadReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadReportActionPerformed(evt);
            }
        });

        lblTotalNumberOfSales.setText("Total No of Sales: ");

        lblAverageSale.setText("Average Sale:");

        lblMinimumSale.setText("Minimum Sale:");

        lblHighestSale.setText(" Highest Sale:");

        lblTotalSalesReport.setText("Total Sales: ");

        lblTotalCustomers.setText("Total Customers: ");

        lblReportBox.setText("Report");

        javax.swing.GroupLayout pnlReportLayout = new javax.swing.GroupLayout(pnlReport);
        pnlReport.setLayout(pnlReportLayout);
        pnlReportLayout.setHorizontalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReportLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalSalesReport)
                            .addComponent(lblTotalNumberOfSales)
                            .addComponent(lblTotalCustomers)
                            .addComponent(lblAverageSale)
                            .addComponent(lblMinimumSale)
                            .addComponent(lblHighestSale)
                            .addComponent(btnClearReport)
                            .addComponent(btnDownloadReport)))
                    .addComponent(lblReportBox))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlReportLayout.setVerticalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReportLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblReportBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addGroup(pnlReportLayout.createSequentialGroup()
                        .addComponent(lblTotalNumberOfSales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalSalesReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalCustomers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAverageSale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMinimumSale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHighestSale)
                        .addGap(28, 28, 28)
                        .addComponent(btnClearReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDownloadReport)))
                .addContainerGap())
        );

        pnlMain.addTab("Report", pnlReport);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblApplicationName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApplicationName)
                            .addComponent(btnExit))))
                .addGap(18, 18, 18)
                .addComponent(pnlMain)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        for (int i = 1; i<=10;i++)
        {
            cmbQuantity.addItem(i);
        }
        
        cmbProductPrice.addItem(new Product("Apple", 0.50));
        cmbProductPrice.addItem(new Product("Orange", 0.75));
        cmbProductPrice.addItem(new Product("Coconut", 2.70));
        cmbProductPrice.addItem(new Product("Pineapple", 1.15));
        cmbProductPrice.addItem(new Product("Mixed Fruits", 4.50));
    }//GEN-LAST:event_formWindowOpened

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        
        Product selectedItem = (Product)cmbProductPrice.getSelectedItem();
        int quantity = (int)cmbQuantity.getSelectedItem();
        
        basket.AddToBasket(selectedItem, quantity);
        
        txtAreaShoppingCart.setText(basket.toString());
        
        lblSalesTotal.setText(String.format("£%.2f", basket.GetTotalPrice()));
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnClearListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearListActionPerformed
        txtAreaShoppingCart.setText("");
        lblSalesTotal.setText("£0.00");
        basket.ClearBasket();
    }//GEN-LAST:event_btnClearListActionPerformed

    private void cmbQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQuantityActionPerformed
        updateTotal();
    }//GEN-LAST:event_cmbQuantityActionPerformed

    private void cmbProductPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductPriceActionPerformed
        updateTotal();
    }//GEN-LAST:event_cmbProductPriceActionPerformed
    private double highestSale;
    private double lowestSale;
    private double totalValueOfSales = 0;
    private int i = 1;
    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        //message box display to user with detailed informations about bought items
        if(txtAreaShoppingCart.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Add an item to the cart to continue!");
            return;
        }else
        {
        JOptionPane.showMessageDialog(
                null, 
                "Products List:\n"  + txtAreaShoppingCart.getText()
                +"\n Cost Total: \n"+ lblSalesTotal.getText(),
                "Check Out", 1);
        }
        //take all the text area box informations and put it into the raport as customer<number>

            if(txtAreaReport.getText().isEmpty())
            {
            txtAreaReport.append( 
                    "Customer " + i
                    + "\n" 
                    + txtAreaShoppingCart.getText() 
                    + "\n" 
                    + lblSalesTotal.getText()
                    +"\n"
                    +"-------------------------------");
                    i++;
            }else
            {
                    txtAreaReport.append( 
                    "\nCustomer " + i
                    + "\n" 
                    + txtAreaShoppingCart.getText() 
                    + "\n" 
                    + lblSalesTotal.getText()
                    +"\n"
                    +"-------------------------------");
                    i++;
            }

            totalValueOfSales += basket.GetTotalPrice();
            //change text of report labels
            lblTotalNumberOfSales.setText("Total No of Sales: " + (i - 1));
            lblTotalSalesReport.setText("Total Sales: " + totalValueOfSales);
            lblTotalCustomers.setText("Total Customers: " + (i-1));
            lblAverageSale.setText("Average Sale: " + (totalValueOfSales / (i-1)));
            if (basket.GetTotalPrice() > highestSale)
            {
                highestSale = basket.GetTotalPrice();
            }
            if (basket.GetTotalPrice() < lowestSale || lowestSale == 0)
            {
                lowestSale = basket.GetTotalPrice();
            }
            lblMinimumSale.setText("Lowest Sale: " + lowestSale);
            lblHighestSale.setText("Highest Sale: " + highestSale);
            
            //clear the basket and shopping cart after adding to report/checking out
            txtAreaShoppingCart.setText("");
            lblSalesTotal.setText("£0.00");
            basket.ClearBasket();
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnClearReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearReportActionPerformed
        txtAreaReport.setText("");
        i = 1;
        lblTotalNumberOfSales.setText("Total No of Sales: ");
        lblAverageSale.setText("Average Sale: ");
        lblMinimumSale.setText("Minimum Sale: ");
        lblHighestSale.setText("Highest Sale: ");
    }//GEN-LAST:event_btnClearReportActionPerformed

    private void btnDownloadReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadReportActionPerformed
        LocalDateTime localdatetime = LocalDateTime.ofInstant(Instant.now(),ZoneId.systemDefault());
        String filenameDate = localdatetime.getDayOfWeek() + " " + localdatetime.getDayOfMonth() + " " + localdatetime.getMonth() + " " + localdatetime.getYear();
        String filename =  filenameDate + " Customer Report.txt";
        JFileChooser fileChooser = new JFileChooser(System.getProperty("user.home") + "\\Desktop");
        fileChooser.setDialogTitle("Save Report");
        fileChooser.setSelectedFile(new File(filename));
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
                try {
                    FileWriter writer = new FileWriter(fileToSave);
                    writer.write(txtAreaReport.getText());
                    writer.close();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Error saving report", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnDownloadReportActionPerformed

    
    private void updateTotal() {
        Product selectedItem = (Product)cmbProductPrice.getSelectedItem();
        int quantity = (int)cmbQuantity.getSelectedItem();
        if(selectedItem != null)
        {
            lblSelectedTotal.setText(quantity + " x £" + selectedItem.Price + " = " + String.format("%.2f", quantity * selectedItem.Price));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simple_Epos_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simple_Epos_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simple_Epos_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simple_Epos_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simple_Epos_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnClearList;
    private javax.swing.JButton btnClearReport;
    private javax.swing.JButton btnDownloadReport;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<diwadikswobarg.Product> cmbProductPrice;
    private javax.swing.JComboBox<Integer> cmbQuantity;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApplicationName;
    private javax.swing.JLabel lblAverageSale;
    private javax.swing.JLabel lblHighestSale;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMinimumSale;
    private javax.swing.JLabel lblProductAndPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblReportBox;
    private javax.swing.JLabel lblSalesTotal;
    private javax.swing.JLabel lblSalesTotalName;
    private javax.swing.JLabel lblSelectedTotal;
    private javax.swing.JLabel lblShoppingCart;
    private javax.swing.JLabel lblTotalCustomers;
    private javax.swing.JLabel lblTotalNumberOfSales;
    private javax.swing.JLabel lblTotalSalesReport;
    private javax.swing.JTabbedPane pnlMain;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JTextArea txtAreaReport;
    private javax.swing.JTextArea txtAreaShoppingCart;
    // End of variables declaration//GEN-END:variables
}
